services:  # 定义服务集合
  allinssl:  # 服务名称为 allinssl
    image: allinssl/allinssl:latest  # 使用的镜像，来自 Docker Hub 的 allinssl 仓库
    container_name: allinssl  # 设置容器名称为 allinssl
    ports:
      - "7979:8888"  # 将主机的 7979 端口映射到容器内的 8888 端口
    volumes:
      - ./www/allinssl/data:/www/allinssl/data  # 挂载本地目录到容器内，保证数据持久化
    environment:
      - ALLINSSL_USER=allinssl  # 设置环境变量：用户名
      - ALLINSSL_PWD=allinssldocker  # 设置环境变量：密码
      - ALLINSSL_URL=allinssl  # 设置环境变量：访问路径或标识
    restart: always  # 设置容器在任何情况下都会自动重启，包括系统重启后
