services:
  brave:
    image: lscr.io/linuxserver/brave:latest
    container_name: brave
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - LC_ALL=zh_CN.UTF-8 # 中文
    volumes:
      - ./config:/config
    ports:
      - 3000:3000 # http端口
      - 3001:3001 # https端口
    shm_size: "1gb"
    restart: unless-stopped
