version: "2.1"
services:
  clouddrive2:                                                          # 定义服务名称
    image: cloudnas/clouddrive2                                         # 使用的镜像，latest表示总是拉取最新版本
    container_name: clouddrive2                                         # 容器的自定义名称
    environment:                                                        # 容器环境变量
      - TZ=Asia/Shanghai                                                # 设置容器时区
      - CLOUDDRIVE_HOME=/Config                                         # clouddrive2 配置路径
    volumes:
      - <path to accept cloud mounts>:/CloudNAS:shared                  # 左边是宿主机路径(可自定义)，右边是容器路径(固定)，用于挂载云盘
      - <path to app data>:/Config                                      # 左边是宿主机路径(可自定义)，右边是容器路径(固定)，应用数据
      - <other local shared path>:/media:shared                         # 左边是宿主机路径(可自定义)，右边是容器路径(固定)，可选媒体路径
    devices:
      - /dev/fuse:/dev/fuse                                             # 容器访问 FUSE 设备
    pid: "host"                                                         # 使用宿主机 PID namespace
    privileged: true                                                    # 授权容器高级权限
    network_mode: "host"                                                # 使用宿主机网络
    restart: always                                                     # 自动重启策略：容器异常退出时自动重启
