version: '3.9'  # docker-compose 文件版本

services:
  easynvr:                                                                # 定义服务名称
    image: registry.cn-shanghai.aliyuncs.com/rustc/easynvr_amd64:latest   # 使用的镜像，来自阿里云镜像仓库，latest 表示最新版本
    container_name: easynvr                                               # 容器的自定义名称
    restart: always                                                       # 自动重启策略：容器异常退出时自动重启
    network_mode: host                                                    # 使用宿主机网络模式

    logging:                                                              # 日志配置
      driver: json-file
      options:
        max-size: "50m"                                                   # 单个日志文件最大尺寸
        max-file: "3"                                                     # 日志文件轮转数量

    deploy:                                                               # 部署资源限制配置
      resources:
        limits:
          memory: 4g                                                      # 容器最大可用内存
        reservations:
          memory: 512m                                                    # 可选：预留内存，提高调度稳定性

    volumes:                                                              # 数据卷挂载配置
      - easynvr_data:/app                                                 # easynvr_data 数据卷，用于存储授权和配置文件持久化
      # - /mnt/video:/app/r                                               # 宿主机录像文件目录(可自定义)，容器录像文件目录(固定)，如需启用请取消注释并修改路径

volumes:
  easynvr_data:                                                           # 定义本地数据卷
    driver: local                                                         # 使用本地卷驱动
