services:
  easynode:
    image: chaoszhu/easynode       # 使用 chaoszhu 发布的 easynode 镜像
    restart: always                # 容器异常退出后自动重启
    ports:
      - 8082:8082                  # 将宿主机的 8082 端口映射到容器的 8082 端口
    volumes:
      - ./easynode/db:/easynode/app/db  # 将当前目录下的 db 文件夹挂载到容器内，实现数据持久化
    environment:
      - TZ=Asia/Shanghai           # 设置容器时区为上海
      - DEBUG=0                    # 关闭调试模式（0 表示关闭，1 表示开启）
