services:
 easy-vdl:                               # 定义服务名称 easy-vdl
  image: qq918652593/easy-vdl:latest     # 使用的镜像，来自 Docker Hub，latest 表示最新版本
  container_name: easy-vdl               # 容器的自定义名称
  ports:
    - 8080:80                            # 左边是宿主机端口(可自定义)，右边是容器端口(固定)
  volumes:
    - ./downloads:/app/downloads         # 左边是宿主机路径(可自定义)，右边是容器路径(固定)
  restart: always                        # 容器异常退出后自动重启
