version: '3'
services:
  filecodebox:                           # 定义服务名称
    image: lanol/filecodebox:beta        # 使用的镜像，来自 Docker Hub，beta 表示测试版本
    container_name: filecodebox          # 容器的自定义名称
    ports:
      - 12345:12345                      # 左边是宿主机端口(可自定义)，右边是容器端口(固定)
    volumes:
      - ./data:/app/data                 # 左边是宿主机路径(可自定义)，右边是容器路径(固定)
    restart: always                      # 自动重启策略：容器异常退出时自动重启
