services:
  mongodb:                        # MongoDB 数据库服务
    image: mongo                  # 使用官方 mongo 镜像
    restart: always               # 容器异常退出时自动重启
    volumes:
      - ./data/mongodb:/data/db   # 持久化 MongoDB 数据到宿主机 ./data/mongodb

  redis:                          # Redis 缓存服务
    image: redis                  # 使用官方 redis 镜像
    restart: always               # 容器异常退出时自动重启
    volumes:
      - ./data/redis:/data        # 持久化 Redis 数据到宿主机 ./data/redis

  fiora:                          # Fiora 聊天服务
    image: suisuijiang/fiora:latest      # 使用指定的 Fiora 镜像
    restart: always               # 容器异常退出时自动重启
    depends_on:                   # 先启动数据库和缓存
      - mongodb
      - redis
    ports:
      - "9200:9200"               # 宿主机 9200 端口映射到容器 9200
    environment:                  # 环境变量
      - Database=mongodb://mongodb/fiora   # Fiora 连接 MongoDB
      - RedisHost=redis                    # Fiora 连接 Redis
