services:
  golink:                                     # 定义服务名称 golink
    image: ghcr.io/tailscale/golink:main      # 使用的镜像，来自 GitHub Container Registry
    container_name: golink                    # 容器的自定义名称
    restart: always                           # 容器异常退出后自动重启
    ports:
      - "8080:8080"                           # 左边是宿主机端口(可自定义)，右边是容器端口(固定)
    command: ["-dev-listen", ":8080"]         # 容器启动命令，监听 8080 端口
    environment:
      - TZ=Asia/Shanghai                      # 设置时区为上海
    volumes:
      - ./data:/home/nonroot                  # 左边是宿主机路径(可自定义)，右边是容器路径(固定)
