services:
  iventoy:                                                                # 定义服务名称
    image: szabis/iventoy:latest                                          # 使用的镜像，来自 Docker Hub，latest 表示最新版本
    network_mode: "host"                                                  # 网络模式：使用宿主机的网络配置
    container_name: iventoy                                               # 容器的自定义名称
    restart: always                                                       # 自动重启策略：容器异常退出时自动重启
    privileged: true #must be true                                        # 必须设置为 true，允许容器访问主机的设备
    environment:
      - AUTO_START_PXE=true                                               # 设置自动启动 PXE 服务
    ports:
      - "67:67/udp" # DHCP Server                                         # DHCP 服务器端口映射（UDP 协议）
      - "69:69/udp" # TFTP Server                                         # TFTP 服务器端口映射（UDP 协议）
      - "10809:10809" # NBD Server (NBD)                                  # NBD 服务器端口映射
      - "16000:16000" # PXE Service HTTP Server (iVentoy PXE Service)     # PXE 服务 HTTP 服务器端口映射（iVentoy PXE 服务）
      - "26000:26000" # PXE GUI HTTP Server (iVentoy GUI)                 # PXE GUI HTTP 服务器端口映射（iVentoy GUI）
    volumes:
      - /path/to/data:/opt/iventoy/data                                   # 左边是宿主机路径（可自定义），右边是容器路径（固定），用于数据存储
      - /path/to/iso:/opt/iventoy/iso                                     # 左边是宿主机路径（可自定义），右边是容器路径（固定），用于存储 ISO 文件
      - /path/to/log:/opt/iventoy/log                                     # 左边是宿主机路径（可自定义），右边是容器路径（固定），用于存储日志文件
      - /path/to/user:/opt/iventoy/user                                   # 左边是宿主机路径（可自定义），右边是容器路径（固定），用于存储用户数据
