services:
  mongo:
    container_name: jmalcloud_mongodb   # MongoDB 容器名称
    image: mongo:7.0
    environment:
      TZ: "Asia/Shanghai"               # 设置时区为上海
    volumes:
      - ./docker/jmalcloud/mongodb/data/db:/data/db   # 映射数据目录
      - ./docker/jmalcloud/mongodb/backup:/dump       # 映射备份目录
    restart: unless-stopped                  # 容器停止时自动重启，除非手动停止
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]   # 健康检查命令
      interval: 10s      # 检查间隔时间
      timeout: 5s        # 超时时间
      retries: 3         # 失败重试次数
    command: --wiredTigerCacheSizeGB 0.5    # 设置 WiredTiger 缓存大小为 0.5GB

  jmalcloud:
    container_name: jmalcloud_server    # 主应用容器名称
    image: jmal/jmalcloud:latest        # 使用 jmalcloud 镜像
    environment:
      MONGODB_URI: "mongodb://mongo:27017/jmalcloud"    # MongoDB 数据库连接地址
      TZ: "Asia/Shanghai"            # 设置时区为上海
      JVM_OPTS: "-Xms512m -Xmx4g"    # 设置 JVM 初始内存和最大内存
      #EXACT_SEARCH: false
      #PUID: 0
      #PGID: 0
      # 如果为空系统会自动生成(位置在/jmalcloud/files/.env)(openssl rand -hex 32)
      ENCRYPTION_SECRET_KEY: ""            # 加密密钥（可选）
      # 如果为空系统会自动生成(位置在/jmalcloud/files/.env)(openssl rand -hex 16)
      ENCRYPTION_SALT: ""                  # 加密盐值（可选）
    volumes:
      - ./docker/jmalcloud/files:/jmalcloud/files/    # 映射文件目录
    restart: unless-stopped            # 容器停止时自动重启，除非手动停止
    ports:
      - 7072:8088           # 映射主应用端口

  nginx:
    container_name: jmalcloud_nginx        # Nginx 容器名称
    image: jmal/jmalcloud-nginx:latest     # 使用 jmalcloud Nginx 镜像
    ports:
      - 7070:80                           # 映射 HTTP 服务端口
      - 7071:8089                         # 映射另一个服务端口
    environment:
      TZ: "Asia/Shanghai"                 # 设置时区为上海
    restart: unless-stopped               # 容器停止时自动重启，除非手动停止
    links:
      - jmalcloud                         # 与主应用容器相连接
      - office                            # 与 Office 容器相连接

  office: # Optional                      # 可选组件：OnlyOffice 文档服务器
    container_name: jmalcloud_office      # OnlyOffice 容器名称
    image: onlyoffice/documentserver:9.0  # 使用 OnlyOffice 9.0 镜像
    environment:
      TZ: "Asia/Shanghai"                 # 设置时区为上海
      JWT_SECRET: "Abcd1Efg2Hjk3mn4o6rsT7uvW8Xyz9"     # OnlyOffice JWT 密钥
    restart: unless-stopped               # 容器停止时自动重启，除非手动停止
