services:  # 服务定义
  katelyatv:  # KatelyaTV 服务
    image: ghcr.io/katelya77/katelyatv:latest  # 使用的镜像
    container_name: katelyatv  # 容器名称
    restart: always  # 总是自动重启
    ports:  # 端口映射
      - "4400:3000"  # 主机4400端口映射到容器3000端口
    environment:  # 环境变量
      - USERNAME=admin  # 管理员用户名
      - PASSWORD=password  # 管理员密码
      - NEXT_PUBLIC_STORAGE_TYPE=kvrocks  # 存储类型设置为kvrocks
      - KVROCKS_URL=redis://kvrocks:6666  # Kvrocks数据库连接地址
      - NEXT_PUBLIC_ENABLE_REGISTER=true  # 启用用户注册功能
    depends_on:  # 依赖关系
      - kvrocks  # 依赖于kvrocks服务
  kvrocks:  # Kvrocks数据库服务
    image: apache/kvrocks:latest  # 使用的Kvrocks镜像
    container_name: kvrocks  # 容器名称
    restart: always  # 总是自动重启
    ports:  # 端口映射
      - "6666:6666"  # 主机6666端口映射到容器6666端口
    volumes:  # 数据卷映射
      - ./kvrocks_data:/data  # 当前目录下的kvrocks_data文件夹映射到容器/data目录
