version: '3.9'
services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - "./db:/var/lib/mysql"                                             #./db是数据库持久化目录，可以修改
    environment:
      - "TZ=Asia/Shanghai"
      - "MYSQL_ROOT_PASSWORD=kodbox"                                      #数据库root密码
      - "MYSQL_DATABASE=kodbox"                                           #数据库名
      - "MYSQL_USER=kodbox"                                               #数据库用户名
      - "MYSQL_PASSWORD=kodbox"                                           #数据库用户密码
    restart: always                                                       # 容器异常退出后自动重启
      
  app:
    image: kodcloud/kodbox                                                # 使用的镜像
    ports:
      - 8080:80                                                           # 左边是主机端口，右边是容器端口
    links:
      - db
      - redis
    volumes:
      - "./site:/var/www/html"                                            #./site是站点目录位置，可以修改
    restart: always
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
  redis:
    image: redis:alpine
    environment:
      - "TZ=Asia/Shanghai"
    restart: always                                                       # 容器异常退出后自动重启
