services:
  memos:                                      # 定义服务名称
    image: ghcr.io/usememos/memos:latest      # 使用的镜像，来自 GitHub Container Registry (GHCR)，latest 表示最新版本
    container_name: memos                     # 容器的自定义名称
    ports:                                    # 端口映射配置 
    - 5230:5230                               # 左边是宿主机端口(可自定义)，右边是容器端口(固定)
    volumes:                                  # 数据卷挂载配置
    - ./data:/var/opt/memos                   # 左边是宿主机 Memos 数据目录(可自定义)，容器数据目录(固定)
    restart: always                           # 自动重启策略：容器异常退出时自动重启
