services:
  memos:
    image: ghcr.io/usememos/memos:latest
    ports:
    - 5230:5230
    volumes:
    - ./data:/var/opt/memos
    restart: always



services:
  memos:
    container_name: memos
    ports:
    - 5230:5230
    volumes:
    - ./data:/var/opt/memos
    image: neosmemo/memos:stable


