version: "3"
services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "8981:8081"              - 左侧的8981端口，可以自定义，与服务器的其余项目端口不冲突即可.
    volumes:
      - /mnt/mydisk/ssd/zdir:/downloads       - volumes:左侧的路径可自定义，冒号右侧的不可更改.
