version: "3"
services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "8981:8081"
    volumes:
      - /mnt/mydisk/ssd/zdir:/downloads
