version: '3'
services:
  moments:                                      # 定义服务名称
    image: kingwrcy/moments:latest              # 容器使用的镜像，latest 表示总是拉取最新版本
    container_name: moments                     # 容器的自定义名称
    environment:                                # 配置环境变量
      PORT: 3000                                # 设置应用运行端口为 3000
      JWT_KEY: $JWT_KEY                         # JWT 密钥，从宿主机环境变量读取（可忽略）
    ports:
      - "3000:3000"                             # 左边是宿主机端口(可自定义)，右边是容器端口(固定)
    volumes:
      - ./data:/app/data                        # 将宿主机 data 文件夹挂载到容器内，实现数据持久化
      - ./etc/localtime:/etc/localtime:ro       # 挂载宿主机本地时间到容器，只读，保证时间一致
      - ./etc/timezone:/etc/timezone:ro         # 挂载宿主机时区文件到容器，只读，保证时区一致
    restart: always                    # 重启策略：容器退出时自动重启
