version: '3.9'
services:
  moontv:
    image: ghcr.io/senshinya/moontv:latest  # 使用来自 GitHub 容器注册表的 MoonTV 镜像（latest 最新版）
    container_name: moontv                 # 容器名称设为 moontv
    restart: always                        # 如果容器停止，则始终自动重启
    ports:
      - '9753:3000'                        # 映射主机的 9753 端口到容器内的 3000 端口
    environment:
      - PASSWORD=password              # 实例访问密码，留空则不启用密码保护（默认空）
      - SITE_NAME=MoonTV               # 站点名称（默认：MoonTV）
      - NEXT_PUBLIC_STORAGE_TYPE=localstorage  # 播放记录/收藏的存储方式（默认：localstorage，可选：localstorage、database【暂不支持】）
      - NEXT_PUBLIC_ENABLE_BLOCKAD=true    # 是否启用智能去广告功能（实验性）（默认：false，可选：true / false）
      - NEXT_PUBLIC_SEARCH_MAX_PAGE=10     # 搜索接口最大可拉取的页数（默认：5，范围：1-50）
      - NEXT_PUBLIC_AGGREGATE_SEARCH_RESULT=true  # 搜索结果是否按标题和年份聚合（默认：true，可选：true / false）

    # 如需自定义配置，可挂载文件
    # volumes:
    #   - ./config.json:/app/config.json:ro

