version: '3.8'

services:
  mtab:                                             # 定义服务名称
    image: itushan/mtab                             # 使用的镜像，来自 Docker Hub，latest 表示最新版本
    container_name: mtab                            # 容器的自定义名称
    ports:                                         
      - "8080:80"                                   # 左边是宿主机端口(可自定义)，右边是容器端口(固定)
    volumes:
      - ./share/docker/mtab/app:/app                # 左边是宿主机路径(可自定义)，右边是容器路径(固定)
    restart: always                                 # 自动重启策略：容器异常退出时自动重启
    depends_on:
      - mysql                                       # 容器依赖关系，确保 mysql 服务先启动
    networks:
      - mtab-network                                # 指定容器网络
  mysql:                                            # 定义服务名称
    image: mysql:8.0                                # 使用的镜像，来自 Docker Hub，latest 表示最新版本
    container_name: mtab-sql                        # 容器的自定义名称
    expose:
      - "3306"                                      # 容器内部端口暴露给其他容器
    environment:                                    # 容器环境变量
      MYSQL_DATABASE: mtab                          # 默认数据库名
      MYSQL_USER: mtab                              # 默认数据库用户名
      MYSQL_PASSWORD: mtab                          # 默认数据库密码
      MYSQL_ROOT_PASSWORD: mtab                     # 默认数据库root密码
    volumes:
      - ./share/docker/mtab/mysql:/var/lib/mysql    # 左边是宿主机路径(可自定义)，右边是容器路径(固定)，用于数据持久化
    restart: always                                 # 自动重启策略：容器异常退出时自动重启
    networks:
      - mtab-network                                # 指定容器网络
networks:
  mtab-network:                                     # 定义自定义网络
    driver: bridge                                  # 使用桥接网络
