version: '3.8'

services:
  mtab:
    image: itushan/mtab
    container_name: mtab
    ports:
      - "8080:80"  #左侧的8080可以自定义
    volumes:
      - ./share/docker/mtab/app:/app
    restart: always
    depends_on:
      - mysql
    networks:
      - mtab-network
  mysql:
    image: mysql:8.0
    container_name: mtab-sql
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: mtab   #默认数据库名
      MYSQL_USER: mtab    #默认数据库用户名
      MYSQL_PASSWORD: mtab   #默认数据库密码
      MYSQL_ROOT_PASSWORD: mtab  #默认数据库root密码
    volumes:
      - ./share/docker/mtab/mysql:/var/lib/mysql  #数据持久化
    restart: always
    networks:
      - mtab-network
networks:
  mtab-network:
    driver: bridge
