services:
  openlist:                                        # 定义服务名称
    image: 'openlistteam/openlist:latest'          # 使用的镜像，来自 Docker Hub，latest 表示最新版本
    container_name: openlist                       # 容器的自定义名称
    user: '0:0'                                    # 设置容器内运行 OpenList 的用户和组为 root (0:0)，可以根据需求修改为其他用户
    volumes:
      - './openlist:/opt/openlist/data'            # 左边是宿主机端口(可自定义)，右边是容器端口(固定)，用于数据持久化
    ports:
      - '5344:5244'                                # 左边是宿主机端口(可自定义)，右边是容器端口(固定)
    environment:
      - PUID=0                                     # 设置容器内运行用户的用户ID为 0 (root)，确保容器权限正确
      - PGID=0                                     # 设置容器内运行用户的组ID为 0 (root)，确保容器权限正确
      - UMASK=022                                  # 设置文件权限掩码为022，表示文件权限为 755（rwxr-xr-x）
    restart: always                                # 自动重启策略：容器异常退出时自动重启
