services:                                       # 定义服务集合，docker-compose 会管理这里的所有服务
  pansou:                                       # 定义服务名称
    image: ghcr.io/fish2018/pansou-web          # 使用的镜像，来自 GitHub 容器仓库，latest 表示最新版本
    container_name: pansou                      # 容器的自定义名称
    ports:                                      # 端口映射配置
      - "22280:80"                              # 左边是宿主机端口(可自定义)，右边是容器端口(固定)
    restart: always                             # 自动重启策略：容器异常退出时自动重启
