version: '3'
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    volumes:
      - ./vw-data:/data  #数据持久化
    ports:
      - "7080:80"  #自定义端口7080可以更改
    restart: always
