version: '3.3' 
services:
    photopea:                                    # 定义服务名称
        image: kovaszab/photopea:latest          # 使用的镜像，来自 Docker Hub，latest 表示最新版本
        container_name: photopea                 # 容器的自定义名称
        ports:
            - '8887:8887'                        # 左边是宿主机端口(可自定义)，右边是容器端口(固定)
        environment:
            - PUID=0                             # 容器运行用户 UID
            - PGID=0                             # 容器运行用户 GID
            - TZ=Asia/Shanghai                   # 设置容器时区为上海
        restart: always                          # 自动重启策略：容器异常退出时自动重启
