services:
  pichome:                                                           # 定义服务名称 pichome
    image: docker.1ms.run/oaooa/pichome:latest                       # 使用的镜像，来自 docker.1ms.run，latest 表示最新版本
    container_name: pichome                                          # 容器的自定义名称
    restart: always                                                  # 自动重启策略：容器异常退出时自动重启
    ports:
      - "18080:80"                                                   # 左边是宿主机端口(可自定义)，右边是容器端口(固定)
      - "18081:443"                                                  # 左边是宿主机端口(可自定义)，右边是容器端口(固定)
    volumes:
      - ./html:/var/www/html                                         # 左边是宿主机目录(可自定义)，右边是容器目录(固定)，用于内容存储
    environment:
      - TZ=Asia/Shanghai                                             # 设置容器时区为上海

  mariadb:                                                           # 定义服务名称 mariadb
    image: docker.1ms.run/linuxserver/mariadb:latest                 # 使用的 MariaDB 镜像，来自 docker.1ms.run，latest 表示最新版本
    container_name: pichome-db                                       # 容器的自定义名称
    restart: always                                                  # 自动重启策略：容器异常退出时自动重启
    environment:
      - MYSQL_DATABASE=pichome                                       # 数据库名称
      - MYSQL_ROOT_PASSWORD=root                                     # root用户密码
      - TZ=Asia/Shanghai                                             # 设置容器时区为上海
      - PUID=1000                                                    # 容器运行用户的 UID
      - PGID=1000                                                    # 容器运行用户的 GID
    volumes:
      - ./db/config:/config                                           # 左边是宿主机目录(可自定义)，右边是容器目录(固定)，用于配置存储
