version: "3.2"
services:
  picoshare:                              # 定义服务名称
    image: mtlynch/picoshare              # 使用的镜像，来自 Docker Hub，latest 表示最新版本
    container_name: picoshare             # 容器的自定义名称
    ports:
      - 4001:4001                         # 左边是宿主机端口(可自定义)，右边是容器端口(固定)
    environment:                          # 容器环境变量
      - PORT=4001                         # 设置容器内部服务端口
      - PS_SHARED_SECRET=Password         # 设置访问密码（请修改为自己的）
    command: -db /data/store.db           # 容器启动命令，指定数据库路径
    volumes:
      - ./data:/data                      # 左边是宿主机路径(可自定义)，右边是容器路径(固定)
    restart: always                       # 自动重启策略：容器异常退出时自动重启
