version: "3.2"
services:
  picoshare:
    image: mtlynch/picoshare
    environment:
      - PORT=4001
      - PS_SHARED_SECRET=Password # 修改成自己的密码
    ports:
      - 4001:4001
    command: -db /data/store.db
    volumes:
      - ./data:/data
