services:
  trilium:
    image: triliumnext/trilium:latest       # 容器使用的镜像，latest 表示总是拉取最新版本
    container_name: trilium                 # 容器名称
    restart: unless-stopped                 # 容器重启策略，除非手动停止，否则自动重启
    environment:
      - TRILIUM_DATA_DIR=/home/node/trilium-data   # 容器内部 Trilium 数据存放路径
    ports:
      - '38080:8080'                        # 端口映射，宿主机 38080 对应容器 8080
    volumes:
      - ./trilium-data:/home/node/trilium-data    # 数据卷映射，宿主机目录持久化容器数据
      - ./etc/timezone:/etc/timezone:ro           # 挂载宿主机时区文件到容器只读，保证时区一致
      - ./etc/localtime:/etc/localtime:ro         # 挂载宿主机本地时间到容器只读，保证时间一致


services:
  trilium-cn:
    image: nriver/trilium-cn                     # 容器使用的镜像，中文汉化版本
    container_name: trilium                      # 容器名称
    restart: always                              # 容器重启策略，除非手动停止，否则自动重启
    ports:
      - "8080:8080"                              # 端口映射，宿主机 38080 对应容器 8080
    volumes:
      - ./trilium-data:/root/trilium-data        # 把同文件夹下的 trilium-data 目录映射到容器内
    environment:
      - TRILIUM_DATA_DIR=/root/trilium-data      # 环境变量表示容器内笔记数据的存储路径
