services:
    web:                                                          # 定义前端服务 web
        image: coolfan1024/uniboard:latest                        # 使用的镜像，来自 Docker Hub，latest 表示最新版本
        container_name: uniboard-web                              # 容器的自定义名称
        ports:
            - '8181:8080'                                         # 左边是宿主机端口(可自定义)，右边是容器端口(固定)
        volumes:
            - ./service/media:/app/service                        # 左边是宿主机路径(可自定义)，右边是容器路径(固定)
        env_file:
            - .env                                                # 指定环境变量文件
        depends_on:
            - db                                                  # 依赖数据库服务 db，确保 db 启动后再启动 web

    db:                                                           # 定义数据库服务 db
        image: postgres:17.4-bookworm                             # 使用的 PostgreSQL 镜像及版本
        container_name: uniboard-db                               # 容器的自定义名称
        env_file:
            - .env                                                # 指定环境变量文件
        volumes:
            - ./database/postgres_data:/var/lib/postgresql/data   # 数据持久化路径，左边宿主机路径可自定义，右边容器路径固定
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres']         # 检查 PostgreSQL 是否可用
            interval: 10s                                         # 每 10 秒检查一次
            timeout: 10s                                          # 超时 10 秒
            retries: 10                                           # 最大重试次数 10 次
