services:
  ytdlp-webui:
    image: marcobaobao/yt-dlp-webui  # 使用的镜像
    container_name: ytdlp-webui  # 容器名称
    ports:
      - "6066:3033"  # 映射端口 3033
    environment:
      - JWT_SECRET=risenetdlp  # 设置 JWT 密钥，用于生成和验证 token
      - TZ=Asia/Shanghai  # 设置容器的时区为上海时区
    volumes:
      - ./downloads:/downloads  # 映射本地的下载目录
    command: --auth --user system --pass Someone --qs 5  # 启用身份验证，设置用户名和密码，并限制并发为 5
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6066"]  # 健康检查，访问 localhost:3033 判断容器是否正常运行
      interval: 30s  # 健康检查的间隔时间
      retries: 3  # 健康检查失败后重试次数
      start_period: 10s  # 启动后等待 10 秒后开始健康检查
      timeout: 10s  # 每次健康检查的超时时间
    restart: always  # 容器停止后总是重启
