version: '3.9'
services:
    zfile:
        image: zhaojun1998/zfile
        volumes:
            - './zfile/file:/data/file'   #这里是文件目录映射后面会用到
            - './zfile/logs:/root/.zfile-v4/logs'
            - './zfile/db:/root/.zfile-v4/db'
        ports:
            - '8080:8080'   #左侧的端口可以自定义
        restart: always
        container_name: zfile
