services:
  torrserver:
    image: ghcr.io/yourok/torrserver
    container_name: torrserver
    restart: always
    ports:
      - '5665:5665'
    volumes:
      - './cache:/opt/ts/torrents'
      - './config:/opt/ts/config'
    environment:
      - TS_PORT=5665
      - TS_DONTKILL=1
      - TS_HTTPAUTH=0