version: '3.9'
services:
  pacman-2:                                                              # 定义服务名称
    image: swr.cn-north-4.myhuaweicloud.com/firfe/pacman-2:2024.09.24    # 使用的镜像，来自华为云 SWR 仓库，版本为 2024.09.24
    container_name: pacman-2                                             # 容器的自定义名称
    network_mode: bridge                                                 # 网络模式使用 bridge
    ports:                                                               # 端口映射配置
      - 3000:3000                                                        # 左边是宿主机端口(可自定义)，右边是容器端口(固定)
    restart: always                                                      # 自动重启策略：容器异常退出时自动重启
    logging:                                                             # 容器日志配置
      options:
        max-size: 1m                                                     # 单个日志文件最大 1MB
        max-file: '3'                                                    # 最多保留 3 个日志文件
