version: '3.9'
services:
  pacman-2:
    container_name: pacman-2
    image: swr.cn-north-4.myhuaweicloud.com/firfe/pacman-2:2024.09.24
    network_mode: bridge
    restart: always
    logging:
      options:
        max-size: 1m
        max-file: '3'
    ports:
      - 3000:3000
