version: '3.9'
services:
  mario-1:
    container_name: mario-1
    image: swr.cn-north-4.myhuaweicloud.com/firfe/mario-1:2025.05.04
    network_mode: bridge
    restart: always
    logging:
      options:
        max-size: 1m
        max-file: '3'
    ports:
      - 3000:3000
